import React from "react";
import { fetchStream } from "../../actions";
import { connect } from "react-redux";

class StreamShow extends React.Component {
  componentDidMount() {
    {
      /* this.props.match is automatically generated by Router */
    }
    this.props.fetchStream(this.props.match.params.id);
  }

  /*
  actions = () => {
    return (
      <React.Fragment>
        <button className='ui button negative' onClick={this.onClick}>
          Delete
        </button>
        <Link to='/' className='ui button'>
          Cancel
        </Link>
      </React.Fragment>
    );
  };
*/

  render() {
    if (!this.props.stream) {
      return <div>Loading....</div>;
    }
    const { title, description } = this.props.stream;
    return (
      <div>
        <div> {title}</div>
        <div>{description}</div>
      </div>
    );
  }
}
const mapStateToProps = (state, ownProps) => {
  return { stream: state.streams[ownProps.match.params.id] };
};

export default connect(mapStateToProps, { fetchStream })(StreamShow);
